"""3D CUBE generation using OpenColorIO Baker and the recipe GroupTransform."""

from __future__ import annotations

from pathlib import Path

import PyOpenColorIO as ocio

from color_core.ocio_manager import OCIOManager
from color_core.recipe import GradeRecipe


def bake_3d_lut(recipe: GradeRecipe, output_path: str, ocio_manager: OCIOManager, lut_size: int | None = None) -> str:
    complete = ocio_manager.complete_recipe(recipe)
    size = lut_size or complete.lut_size
    if size not in (33, 65):
        raise ValueError("LUT size must be 33 or 65")

    if Path(ocio_manager.config_id).is_file():
        config = ocio.Config.CreateFromFile(ocio_manager.config_id)
    else:
        config = ocio.Config.CreateFromBuiltinConfig(ocio_manager.config_id)

    target_name = "LocalColorService Grade Output"
    target = ocio.ColorSpace(referenceSpace=ocio.REFERENCE_SPACE_SCENE)
    target.setName(target_name)
    target.setDescription("ACEScct grade represented by Local Color Service OCIO GroupTransform")
    target.setTransform(ocio_manager.build_grade_group(complete), ocio.COLORSPACE_DIR_FROM_REFERENCE)
    config.addColorSpace(target)
    config.validate()

    baker = ocio.Baker()
    baker.setConfig(config)
    baker.setFormat("iridas_cube")
    baker.setInputSpace(complete.input_color_space)
    baker.setTargetSpace(target_name)
    baker.setCubeSize(size)
    cube = baker.bake()
    if f"LUT_3D_SIZE {size}" not in cube:
        raise RuntimeError("OCIO Baker did not produce the requested 3D CUBE")

    header = (
        "# Generated by Local Color Service V0.2.0 using OpenColorIO Baker\n"
        f"# Recipe Hash: {complete.recipe_hash}\n"
        f"# OCIO Config: {complete.ocio_config_id}\n"
    )
    output = Path(output_path).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(header + cube, encoding="utf-8", newline="\n")
    return str(output)
